apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: kube-logging
spec:
  serviceName: elasticsearch # StatefulSet will be accessable via es-cluster-[0,1,2].elasticsearch.kube-logging.svc.cluster.local
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
        ports: # Open for REST API and inter-node communication.
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name # Resolves to es-cluster-[0,1,2]
          - name: discovery.seed_hosts # Sets a list of master-eligible nodes proactively
            value: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch"
          - name: cluster.initial_master_nodes # Sets a list of master-eligible nodes that will participate in master election
            value: "es-cluster-0,es-cluster-1,es-cluster-2" # Note: node.name not hostname here.
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
      initContainers: # Run to completion before the actual containers are spun up.
      - name: fix-permissions # By default, K8s mounts the data dir as root, which we don't want, because ES can't access it that way.
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"] # 1000 is the Elasticsearch user's UID.
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map # By default these may be too low, resulting in memory capacity errors.
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit # Increases the max number of open file descriptors.
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
