apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter-interface
spec:
  template:
    spec:
      containers:
      - name: kube-hunter-interface
        image: aquasec/kube-hunter 
        command: ["kube-hunter"]
        args: ["--interface"]
      restartPolicy: Never
  backoffLimit: 4
