kind: Service
apiVersion: v1
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
