kind: Service
apiVersion: v1
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP
