kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-viewer
rules:
- apiGroups: [""] # Indicates the core API group.
  resources: ["pods"]
  verbs: ["get", "watch", "list"]